/**
 * Created by eastiming on 16/7/12.
 * Action静态变量
 */

export const API_REQUEST = 'API_REQUEST';
export const API_SUCCESS = 'API_SUCCESS';
export const API_FAILURE = 'API_FAILURE';
export const API_RESET_RESPONSE = 'API_RESET_RESPONSE';

export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';
export const SET_MESSAGE = 'SET_MESSAGE';

export const SIGN_OUT = 'SIGN_OUT';

export const INIT_EXPIRES = 'INIT_EXPIRES';

export const INIT_STORAGE_INFO = 'INIT_STORAGE_INFO';
export const CHECK_TOKEN = 'CHECK_TOKEN';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_RESET_RESPONSE = 'REGISTER_RESET_RESPONSE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_RESET_RESPONSE = 'LOGIN_RESET_RESPONSE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAILURE = 'USER_INFO_FAILURE';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAILURE = 'USER_PROFILE_FAILURE';

export const REFRESHING_TOKEN = 'REFRESHING_TOKEN';
export const REFRESHED_TOKEN = 'REFRESHED_TOKEN';
export const EXPIRE = 'EXPIRE';